# config.example.yaml 请**不要**上传您的config.yaml文件
server:
    port: "8888"                        # type: string 服务器监听的端口


database:                               # 数据库
    username: "username"                # 数据库用户
    password: "password"                # 密码
    address: "address:port"             # 数据库地址
    dbname: "databaseName"              # 数据表名

secret: "something"                     # 用于管理员查看招新信息的密码，确定好后通过其他方式发送给内部人员。
secret2: "secret2"                      # 用于会长团查看详细信息, 应当与secret不同
email:                                  # 配置邮件发送
    sender: "example@example.com"       # 发信信箱
    pwd: "your email token"             # 发信信箱秘密啊
    smtp_addr: "smtp.qq.com"            # 默认为qq邮箱
    smtp_port: 25                       # qq邮箱的端口是25
    receiver: "another email"           # 接受信息的管理员邮箱

dev: true                               # 是否为开发环境

jwt:                                    # JWT 配置
  expires : 48                          # 过期时间(单位:小时)
  issuer  : "issuer"                    # 发行人 
  secret : "Secret"                     # 密钥